version: '3.8'

services:
  balance:
    build: ./
#    command: ["./wait-for-postgres.sh postgres", "./balance"]
    container_name: balance
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=postgres

  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=postgres
